// <auto-generated />
using G5.NetITIMVCDay04.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G5.NetITIMVCDay04.Migrations
{
    [DbContext(typeof(CompanyContext))]
    partial class CompanyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("G5.NetITIMVCDay04.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Social Media"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("G5.NetITIMVCDay04.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ismailia",
                            Age = 22,
                            DepartmentId = 1,
                            Email = "email@mail.com",
                            Name = "Ramy",
                            Salary = 1234m
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ismailia",
                            Age = 32,
                            DepartmentId = 2,
                            Email = "email@mail.com",
                            Name = "Mai",
                            Salary = 2234m
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ismailia",
                            Age = 42,
                            DepartmentId = 3,
                            Email = "email@mail.com",
                            Name = "Ali",
                            Salary = 3234m
                        },
                        new
                        {
                            Id = 4,
                            Address = "Ismailia",
                            Age = 52,
                            DepartmentId = 4,
                            Email = "email@mail.com",
                            Name = "Omar",
                            Salary = 4234m
                        },
                        new
                        {
                            Id = 5,
                            Address = "Ismailia",
                            Age = 28,
                            DepartmentId = 1,
                            Email = "email@mail.com",
                            Name = "Mostafa",
                            Salary = 5234m
                        },
                        new
                        {
                            Id = 6,
                            Address = "Ismailia",
                            Age = 38,
                            DepartmentId = 2,
                            Email = "email@mail.com",
                            Name = "Ahmed",
                            Salary = 6234m
                        },
                        new
                        {
                            Id = 7,
                            Address = "Ismailia",
                            Age = 48,
                            DepartmentId = 3,
                            Email = "email@mail.com",
                            Name = "Sara",
                            Salary = 7234m
                        },
                        new
                        {
                            Id = 8,
                            Address = "Ismailia",
                            Age = 26,
                            DepartmentId = 4,
                            Email = "email@mail.com",
                            Name = "Osama",
                            Salary = 8234m
                        },
                        new
                        {
                            Id = 9,
                            Address = "Ismailia",
                            Age = 36,
                            DepartmentId = 1,
                            Email = "email@mail.com",
                            Name = "Mohamed",
                            Salary = 9234m
                        },
                        new
                        {
                            Id = 10,
                            Address = "Ismailia",
                            Age = 46,
                            DepartmentId = 2,
                            Email = "email@mail.com",
                            Name = "Nour",
                            Salary = 10234m
                        },
                        new
                        {
                            Id = 11,
                            Address = "Ismailia",
                            Age = 46,
                            DepartmentId = 3,
                            Email = "email@mail.com",
                            Name = "Mohamed",
                            Salary = 10234m
                        },
                        new
                        {
                            Id = 12,
                            Address = "Ismailia",
                            Age = 46,
                            DepartmentId = 4,
                            Email = "email@mail.com",
                            Name = "Nour",
                            Salary = 10234m
                        });
                });

            modelBuilder.Entity("G5.NetITIMVCDay04.Models.Employee", b =>
                {
                    b.HasOne("G5.NetITIMVCDay04.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("G5.NetITIMVCDay04.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
